# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
ckan:
  container_name: ckan
  # Note, if you are working on CKAN core, change this to
  # build ../../
  image: ckan/ckan:latest
  links:
      - solr
      - redis
  ports:
      - "80:5000"
  environment:
      - CKAN_SQLALCHEMY_URL=postgres://ckan_default@172.17.0.1/ckan_default
      - CKAN_REDIS_URL=redis://redis:6379/0
      - SOLR_URL=http://solr:8983/solr
      - CKAN_SITE_URL=http://localhost/
      - CKAN_LEVEL=DEBUG

solr:
  container_name: solr
  image: ckan/solr:latest
  ports:
      - "8983:8983"

redis:
  container_name: redis
  image: redis:latest
